---
# BUCKET - Speciality
apiVersion: bucket/v1
kind: Schema
metadata:
  name: teacher-speciality
spec:
  title: Teacher Speciality
  description: Teacher Speciality Bucket
  icon: view_stream
  primary: name
  readOnly: false
  history: false
  properties:
    name:
      type: string
      title: name
      description: Name of Speciality
      options:
        position: left
  acl:
    write: true==true
    read: true==true
  order: 35
---
# BUCKET - Fitness Video
apiVersion: bucket/v1
kind: Schema
metadata:
  name: fitness-video
spec:
  title: Video
  description: Video Bucket
  icon: view_stream
  primary: name
  readOnly: false
  history: false
  properties:
    name:
      type: string
      title: name
      description: Name of Video
      options:
        position: left
    description:
      type: textarea
      title: description
      description: Description of Video
      options:
        position: right
    image:
      type: storage
      title: image
      description: Image of Video
      options:
        position: bottom
    vip:
      type: boolean
      title: vip
      description: Is it only available for vip person ?
      options:
        position: bottom
      default: false
    duration:
      type: number
      title: duration
      description: Duration of Video
      options:
        position: bottom
    video:
      type: storage
      title: video
      description: Video File
      options:
        position: bottom
    upload_date:
      type: date
      title: upload_date
      description: Entry Upload Date
      options:
        position: bottom
      default: :created_at
  acl:
    write: true==true
    read: true==true
  order: 29
---
# BUCKET - Fitness User
apiVersion: bucket/v1
kind: Schema
metadata:
  name: fitness-user
spec:
  title: User
  description: User Bucket
  icon: view_stream
  primary: mail
  readOnly: false
  history: false
  properties:
    name:
      type: string
      title: name
      description: Name of User
      options:
        position: left
    surname:
      type: string
      title: surname
      description: Surname of User
      options:
        position: bottom
    gender:
      type: string
      title: gender
      description: Gender of User
      options:
        position: bottom
      enum:
        - male
        - female
        - other
    vip:
      type: boolean
      title: vip
      description: Is this User Vip?
      options:
        position: bottom
      default: false
    birthdate:
      type: date
      title: birthdate
      description: Birthdate of User
      options:
        position: bottom
    created_at:
      type: date
      title: created_at
      description: Entry created date
      options:
        position: bottom
      default: :created_at
    phone_number:
      type: string
      title: phone_number
      description: Number of User
      options:
        position: bottom
    mail:
      type: string
      title: mail
      description: Mail of User
      options:
        position: bottom
  acl:
    write: true==true
    read: true==true
  order: 24
---
# BUCKET - Fitness Teacher
apiVersion: bucket/v1
kind: Schema
metadata:
  name: fitness-teacher
spec:
  title: Teacher
  description: Teacher Bucket
  icon: view_stream
  primary: mail
  readOnly: false
  history: false
  properties:
    name:
      type: string
      title: name
      description: Name of Teacher
      options:
        position: left
    surname:
      type: string
      title: surname
      description: Surname of Teacher
      options:
        position: bottom
    mail:
      type: string
      title: mail
      description: Mail of Teacher
      options:
        position: bottom
    phone_number:
      type: string
      title: phone_number
      description: Phone Number of Teacher
      options:
        position: bottom
    gender:
      type: string
      title: gender
      description: Gender of Teacher
      options:
        position: bottom
      enum:
        - male
        - female
        - other
    picture:
      type: storage
      title: picture
      description: Profile Picture of Teacher
      options:
        position: bottom
    birthday:
      type: date
      title: birthday
      description: Birthday of Teacher
      options:
        position: bottom
    created_at:
      type: date
      title: created_at
      description: Entry created date
      options:
        position: bottom
      default: :created_at
    speciality:
      type: relation
      title: speciality
      description: Speciality of Teacher
      options:
        position: bottom
      relationType: onetoone
      dependent: false
      bucket:
        resourceFieldRef:
          schemaName: teacher-speciality
  acl:
    write: true==true
    read: true==true
  order: 25
---
# BUCKET - Fitness Video Category
apiVersion: bucket/v1
kind: Schema
metadata:
  name: fitness-video-category
spec:
  title: Category
  description: Category Bucket
  icon: view_stream
  primary: name
  readOnly: false
  history: false
  properties:
    name:
      type: string
      title: name
      description: Name of Category
      options:
        position: left
    description:
      type: textarea
      title: description
      description: Description of Category
      options:
        position: right
    image:
      type: storage
      title: image
      description: Image of Category
      options:
        position: bottom
  acl:
    write: true==true
    read: true==true
  order: 26
---
# BUCKET - Fitness Video Packet
apiVersion: bucket/v1
kind: Schema
metadata:
  name: fitness-video-packet
spec:
  title: Video Packet
  description: Packet of Videos
  icon: view_stream
  primary: name
  readOnly: false
  history: false
  properties:
    name:
      type: string
      title: name
      description: Title of packet
      options:
        position: left
    videos:
      type: relation
      title: videos
      description: Videos of Packet
      options:
        position: bottom
      relationType: onetomany
      dependent: false
      primary: name
      bucket:
        resourceFieldRef:
          schemaName: fitness-video
  acl:
    write: true==true
    read: true==true
  order: 27
---
# BUCKET - Fitness Food Program
apiVersion: bucket/v1
kind: Schema
metadata:
  name: fitness-food-program
spec:
  title: Food Program
  description: Food Program Bucket
  icon: view_stream
  primary: name
  readOnly: false
  history: false
  properties:
    name:
      type: string
      title: name
      description: Name of Program
      options:
        position: left
    user:
      type: relation
      title: user
      description: User of Program
      options:
        position: bottom
      relationType: onetoone
      dependent: false
      primary: mail
      bucket:
        resourceFieldRef:
          schemaName: fitness-user
    teacher:
      type: relation
      title: teacher
      description: Teacher of Program
      options:
        position: bottom
      relationType: onetoone
      dependent: false
      primary: mail
      bucket:
        resourceFieldRef:
          schemaName: fitness-teacher
    created_at:
      type: date
      title: created_at
      description: Entry created date
      options:
        position: bottom
      default: :created_at
  acl:
    write: true==true
    read: true==true
  order: 28
---
# BUCKET - Fitness Video
apiVersion: bucket/v1
kind: Schema
metadata:
  name: fitness-video
spec:
  title: Video
  description: Video Bucket
  icon: view_stream
  primary: name
  readOnly: false
  history: false
  properties:
    name:
      type: string
      title: name
      description: Name of Video
      options:
        position: left
    description:
      type: textarea
      title: description
      description: Description of Video
      options:
        position: right
    image:
      type: storage
      title: image
      description: Image of Video
      options:
        position: bottom
    vip:
      type: boolean
      title: vip
      description: Is it only available for vip person ?
      options:
        position: bottom
      default: false
    duration:
      type: number
      title: duration
      description: Duration of Video
      options:
        position: bottom
    video:
      type: storage
      title: video
      description: Video File
      options:
        position: bottom
    teacher:
      type: relation
      title: teacher
      description: Teacher of Video
      options:
        position: bottom
      relationType: onetoone
      dependent: false
      bucket:
        resourceFieldRef:
          schemaName: fitness-teacher
    category:
      type: relation
      title: category
      description: Category of Video
      options:
        position: bottom
      relationType: onetoone
      dependent: false
      bucket:
        resourceFieldRef:
          schemaName: fitness-video-category
    upload_date:
      type: date
      title: upload_date
      description: Entry Upload Date
      options:
        position: bottom
      default: :created_at
  acl:
    write: true==true
    read: true==true
  order: 29
---
# BUCKET - Fitness Weekly Program
apiVersion: bucket/v1
kind: Schema
metadata:
  name: fitness-weekly-program
spec:
  title: Weekly Program
  description: Weekly Program Bucket
  icon: view_stream
  primary: name
  readOnly: false
  history: false
  properties:
    name:
      type: string
      title: name
      description: Name of Weekly Program
      options:
        position: left
    description:
      type: textarea
      title: description
      description: Description of Weekly Program
      options:
        position: right
    created_at:
      type: date
      title: created_at
      description: Entry created date
      options:
        position: bottom
      default: :created_at
  acl:
    write: true==true
    read: true==true
  order: 30
---
# BUCKET - Fitness Performance
apiVersion: bucket/v1
kind: Schema
metadata:
  name: fitness-performance
spec:
  title: Performance
  description: Performance of User
  icon: view_stream
  primary: title
  readOnly: false
  history: false
  properties:
    title:
      type: string
      title: title
      description: Title of Performance
      options:
        position: bottom
    user:
      type: relation
      title: user
      description: User of Performance
      options:
        position: bottom
      relationType: onetoone
      dependent: false
      primary: mail
      bucket:
        resourceFieldRef:
          schemaName: fitness-user
    teacher:
      type: relation
      title: teacher
      description: Teacher of Performance
      options:
        position: bottom
      relationType: onetoone
      dependent: false
      primary: mail
      bucket:
        resourceFieldRef:
          schemaName: fitness-teacher
    metrics:
      type: array
      title: metrics
      description: Metrics of Performance
      options:
        position: bottom
      items:
        title: Items of Metrics
        type: object
        properties:
          value:
            type: number
            title: value
            description: Value of Item
            options:
              position: bottom
          metric:
            type: relation
            title: metric
            description: Metric of Item
            options:
              position: bottom
            relationType: onetoone
            dependent: false
            bucket:
              resourceFieldRef:
                schemaName: fitness-metric
    created_at:
      type: date
      title: created_at
      description: Entry created date
      options:
        position: bottom
      default: :created_at
  acl:
    write: true==true
    read: true==true
  order: 31
---
# BUCKET - Fitness Metric
apiVersion: bucket/v1
kind: Schema
metadata:
  name: fitness-metric
spec:
  title: Metric
  description: Metric Bucket
  icon: view_stream
  primary: name
  readOnly: false
  history: false
  properties:
    name:
      type: string
      title: name
      description: Name of Metric
      options:
        position: left
    unit:
      type: string
      title: unit
      description: Unit of Metric
      options:
        position: bottom
  acl:
    write: true==true
    read: true==true
  order: 32
---
# BUCKET - Fitness training
apiVersion: bucket/v1
kind: Schema
metadata:
  name: fitness-training
spec:
  title: Training
  description: User Training
  icon: view_stream
  primary: name
  readOnly: false
  history: false
  properties:
    name:
      type: string
      title: name
      description: Name of Training
      options:
        position: left
    user:
      type: relation
      title: user
      description: User of Training
      options:
        position: bottom
      relationType: onetomany
      dependent: false
      primary: mail
      bucket:
        resourceFieldRef:
          schemaName: fitness-user
    packet:
      type: relation
      title: packet
      description: Packet of Training
      options:
        position: bottom
      relationType: onetomany
      dependent: false
      primary: title
      bucket:
        resourceFieldRef:
          schemaName: fitness-video-packet
    teacher:
      type: relation
      title: teacher
      description: Teacher of Training
      options:
        position: bottom
      relationType: onetoone
      dependent: false
      bucket:
        resourceFieldRef:
          schemaName: fitness-teacher
  acl:
    write: true==true
    read: true==true
  order: 33
---
# BUCKET - Watched Video
apiVersion: bucket/v1
kind: Schema
metadata:
  name: fitness-my-watched-video
spec:
  title: Watched Video
  description: Watched Video of User
  icon: view_stream
  primary: name
  readOnly: false
  history: false
  properties:
    name:
      type: string
      title: name
      description: Name
      options:
        position: left
    user:
      type: relation
      title: user
      description: User of Watched Video
      options:
        position: bottom
      relationType: onetoone
      dependent: false
      primary: mail
      bucket:
        resourceFieldRef:
          schemaName: fitness-user
    video:
      type: relation
      title: video
      description: Video of Watched Video
      options:
        position: bottom
      relationType: onetoone
      dependent: false
      primary: name
      bucket:
        resourceFieldRef:
          schemaName: fitness-video
  acl:
    write: true==true
    read: true==true
  order: 34
